laguage: java
jdk:
  - oraclejdk8
install:
  - mvn package -P sonatype -D skipTests
script:
  - mvn install -P sonatype
  - mvn -f example versions:use-latest-versions -Dincludes=org.tinyj.web:tinyj-web-mvc -DallowSnapshots=true
  - mvn -f example verify
